-- BYT Club Wallet Supabase/PostgreSQL schema
-- This schema uses bigint identity primary keys because the current prototype
-- stores numeric ids, including Date.now() values, in localStorage.

create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists members (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique,
  whatsapp text,
  balance numeric(10, 2) not null default 0,
  status text not null default 'active',
  member_type text,
  package_type text,
  package_name text,
  package_price numeric default 0,
  package_credit numeric default 0,
  registration_fee numeric default 0,
  gift_choice text,
  uniform_size text,
  gender text,
  birthday text,
  emergency_contact text,
  registration_payment_proof_name text,
  registration_payment_proof_url text,
  agreed_terms boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint members_status_check check (status in ('active', 'inactive', 'pending')),
  constraint members_member_type_check check (
    member_type is null or member_type in ('new', 'regular', 'guest')
  )
);

alter table members add column if not exists whatsapp text;
alter table members add column if not exists package_type text;
alter table members add column if not exists package_name text;
alter table members add column if not exists package_price numeric default 0;
alter table members add column if not exists package_credit numeric default 0;
alter table members add column if not exists registration_fee numeric default 0;
alter table members add column if not exists gift_choice text;
alter table members add column if not exists uniform_size text;
alter table members add column if not exists gender text;
alter table members add column if not exists birthday text;
alter table members add column if not exists emergency_contact text;
alter table members add column if not exists registration_payment_proof_name text;
alter table members add column if not exists registration_payment_proof_url text;
alter table members add column if not exists agreed_terms boolean default false;

create table if not exists app_users (
  id bigint generated by default as identity primary key,
  member_id bigint references members(id) on delete set null,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_users_role_check check (role in ('admin', 'member'))
);

create table if not exists reload_requests (
  id bigint generated by default as identity primary key,
  member_id bigint not null references members(id) on delete restrict,
  member_name text,
  amount numeric(10, 2) not null,
  status text not null default 'Pending',
  date date not null default current_date,
  payment_screenshot text,
  screenshot_name text,
  screenshot_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reload_requests_amount_check check (amount > 0),
  constraint reload_requests_status_check check (
    status in ('Pending', 'Approved', 'Rejected')
  )
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  member_id bigint not null references members(id) on delete restrict,
  date date not null default current_date,
  description text not null,
  amount numeric(10, 2) not null,
  type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint transactions_type_check check (
    type is null or type in (
      'reload',
      'session_charge',
      'manual_expense',
      'manual_adjustment',
      'other'
    )
  )
);

create table if not exists sessions (
  id bigint generated by default as identity primary key,
  date date not null,
  time text not null,
  venue text not null,
  court_count integer not null,
  max_players integer not null,
  court_fee_total numeric(10, 2) not null,
  cancel_cutoff time,
  walk_in_limit integer not null default 5,
  status text not null default 'open',
  charge_status text not null default 'not_charged',
  shuttlecock_used integer not null default 0,
  shuttlecock_rate numeric(10, 2) not null default 0,
  other_fee_total numeric(10, 2) not null default 0,
  charged_at timestamptz,
  finalized_court_charge_per_player numeric(10, 2),
  finalized_attended_charge_per_player numeric(10, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sessions_court_count_check check (court_count > 0),
  constraint sessions_max_players_check check (max_players > 0),
  constraint sessions_court_fee_total_check check (court_fee_total >= 0),
  constraint sessions_shuttlecock_used_check check (shuttlecock_used >= 0),
  constraint sessions_shuttlecock_rate_check check (shuttlecock_rate >= 0),
  constraint sessions_other_fee_total_check check (other_fee_total >= 0),
  constraint sessions_status_check check (status in ('open', 'closed')),
  constraint sessions_charge_status_check check (
    charge_status in ('not_charged', 'charged')
  )
);

create table if not exists session_bookings (
  id bigint generated by default as identity primary key,
  session_id bigint not null references sessions(id) on delete cascade,
  member_id bigint not null references members(id) on delete restrict,
  status text not null default 'booked',
  booked_at timestamptz not null default now(),
  cancelled_at timestamptz,
  status_updated_at timestamptz,
  walk_in_count integer not null default 0,
  walk_in_names text[] not null default '{}',
  member_attached_walkin_charge_mode text not null default 'collect_separately',
  late_cancelled_walk_in_count integer not null default 0,
  late_cancelled_walk_in_names text[] not null default '{}',
  waitlist_type text,
  waitlist_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint session_bookings_status_check check (
    status in ('booked', 'attended', 'no_show', 'late_cancel', 'cancelled')
  ),
  constraint session_bookings_member_attached_walkin_charge_mode_check check (
    member_attached_walkin_charge_mode in (
      'collect_separately',
      'deduct_walkin_fee',
      'charge_as_member'
    )
  )
);

alter table sessions add column if not exists walk_in_limit integer not null default 5;

alter table session_bookings add column if not exists walk_in_count integer not null default 0;
alter table session_bookings add column if not exists walk_in_names text[] not null default '{}';
alter table session_bookings add column if not exists member_attached_walkin_charge_mode text not null default 'collect_separately';
alter table session_bookings add column if not exists late_cancelled_walk_in_count integer not null default 0;
alter table session_bookings add column if not exists late_cancelled_walk_in_names text[] not null default '{}';
alter table session_bookings add column if not exists waitlist_type text;
alter table session_bookings add column if not exists waitlist_status text;

create index if not exists idx_app_users_member_id on app_users(member_id);
create index if not exists idx_app_users_role on app_users(role);

create index if not exists idx_reload_requests_member_id on reload_requests(member_id);
create index if not exists idx_reload_requests_status on reload_requests(status);
create index if not exists idx_reload_requests_date on reload_requests(date);

create index if not exists idx_transactions_member_id on transactions(member_id);
create index if not exists idx_transactions_date on transactions(date);
create index if not exists idx_transactions_type on transactions(type);

create index if not exists idx_sessions_date on sessions(date);
create index if not exists idx_sessions_status on sessions(status);
create index if not exists idx_sessions_charge_status on sessions(charge_status);

create index if not exists idx_session_bookings_session_id on session_bookings(session_id);
create index if not exists idx_session_bookings_member_id on session_bookings(member_id);
create index if not exists idx_session_bookings_status on session_bookings(status);

drop trigger if exists set_members_updated_at on members;
create trigger set_members_updated_at
before update on members
for each row execute function update_updated_at_column();

drop trigger if exists set_app_users_updated_at on app_users;
create trigger set_app_users_updated_at
before update on app_users
for each row execute function update_updated_at_column();

drop trigger if exists set_reload_requests_updated_at on reload_requests;
create trigger set_reload_requests_updated_at
before update on reload_requests
for each row execute function update_updated_at_column();

drop trigger if exists set_transactions_updated_at on transactions;
create trigger set_transactions_updated_at
before update on transactions
for each row execute function update_updated_at_column();

drop trigger if exists set_sessions_updated_at on sessions;
create trigger set_sessions_updated_at
before update on sessions
for each row execute function update_updated_at_column();

drop trigger if exists set_session_bookings_updated_at on session_bookings;
create trigger set_session_bookings_updated_at
before update on session_bookings
for each row execute function update_updated_at_column();

comment on table members is
  'Club member profiles, balances, and membership status.';

comment on table app_users is
  'Application login accounts for admins and members; member accounts may link to members.';

comment on table reload_requests is
  'Member top-up requests with payment screenshot references and approval status.';

comment on table transactions is
  'Ledger entries that increase or decrease a member wallet balance.';

comment on table sessions is
  'Badminton session setup, booking availability, and finalized charge metadata.';

comment on table session_bookings is
  'Member bookings for sessions, including attendance, cancellation, and no-show status.';
