create table if not exists activity_logs (
  id bigint generated by default as identity primary key,
  actor_role text,
  actor_name text,
  actor_id text,
  action text not null,
  target_type text,
  target_id text,
  description text,
  created_at timestamp with time zone default now()
);

create index if not exists idx_activity_logs_created_at on activity_logs(created_at);
create index if not exists idx_activity_logs_actor_role on activity_logs(actor_role);
create index if not exists idx_activity_logs_action on activity_logs(action);
create index if not exists idx_activity_logs_target_type on activity_logs(target_type);
